from .network_config import NETWORK_COVERAGE_HEIGHT, NETWORK_COVERAGE_WIDTH

# ---------------------------
# User Equipment (UE) Configuration
# ---------------------------
UE_BOUNDARY_BUFFER = 50
UE_BOUNDARY_X_MIN = UE_BOUNDARY_BUFFER
UE_BOUNDARY_X_MAX = NETWORK_COVERAGE_WIDTH - UE_BOUNDARY_BUFFER
UE_BOUNDARY_Y_MIN = UE_BOUNDARY_BUFFER
UE_BOUNDARY_Y_MAX = NETWORK_COVERAGE_HEIGHT - UE_BOUNDARY_BUFFER
UE_DEFAULT_TIMEOUT = 10
UE_DEFAULT_SPAWN_RATE_MIN = 1
UE_DEFAULT_SPAWN_RATE_MAX = 5
UE_SPEED_MIN = 0
UE_SPEED_MAX = 5
UE_MAX_COUNT = 100
UE_REFRESH_PORTION = 0.8
UE_SERVING_BS_HISTORY_LENGTH= 10